Update migarate

diff --git a/.github/workflows/cnc-blog-api-testing.yml b/.github/workflows/cnc-blog-api-testing.yml
--- a/.github/workflows/cnc-blog-api-testing.yml
+++ b/.github/workflows/cnc-blog-api-testing.yml
@@ -1,6 +1,3 @@
-# This workflow will build a .NET project
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
-
 name: Blog.API
 
 on:
@@ -36,11 +33,24 @@ jobs:
       run: |
         cd Blog.API
         dotnet test --no-build --verbosity normal
+    - name: Upload build artifacts
+      uses: actions/upload-artifact@v2
+      with:
+        name: app-artifacts
+        path: |
+          Blog.API/publish/
+          Blog.API/appsettings.json
 
   migrate:
     runs-on: self-hosted
     needs: build
     steps:
+      - name: Download artifacts
+        uses: actions/download-artifact@v2
+        with:
+          name: app-artifacts
+          path: Blog.API
+
       - name: Read connection string
         id: get-connection-string
         run: |
@@ -60,26 +70,33 @@ jobs:
           cd Blog.API
           dotnet ef database update --connection "${{ env.connection_string }}"
         shell: powershell
-        
+
   deploy:
     runs-on: self-hosted
-    needs: build
+    needs: [build, migrate] 
     steps:
-    - name: Kill processes
-      run: |
-        echo "Stopping processes that might be using the files..."
-        handle.exe C:\inetpub\wwwroot\apitesting.cafencode.ddns.net | ForEach-Object {
-          if ($_ -match 'pid: (\d+)') {
-            $pid = $matches[1]
-            taskkill /PID $pid /F
+      - name: Download artifacts
+        uses: actions/download-artifact@v2
+        with:
+          name: app-artifacts
+          path: Blog.API
+          
+      - name: Kill processes
+        run: |
+          echo "Stopping processes that might be using the files..."
+          handle.exe C:\inetpub\wwwroot\apitesting.cafencode.ddns.net | ForEach-Object {
+            if ($_ -match 'pid: (\d+)') {
+              $pid = $matches[1]
+              taskkill /PID $pid /F
+            }
           }
-        }
-    - name: Deploy
-      run: |
-        cd Blog.API
-        echo "Copying files to the web root..."
-        robocopy ./publish "C:\inetpub\wwwroot\apitesting.cafencode.ddns.net" /E /Z
-        $robocopyExitCode = $LASTEXITCODE
-        if ($robocopyExitCode -ge 8) { echo "File copy failed with exit code $robocopyExitCode"; exit $robocopyExitCode }
-        echo "Complete Copy files to the web root."
-        exit 0
+
+      - name: Deploy
+        run: |
+          cd Blog.API
+          echo "Copying files to the web root..."
+          robocopy ./publish "C:\inetpub\wwwroot\apitesting.cafencode.ddns.net" /E /Z
+          $robocopyExitCode = $LASTEXITCODE
+          if ($robocopyExitCode -ge 8) { echo "File copy failed with exit code $robocopyExitCode"; exit $robocopyExitCode }
+          echo "Complete Copy files to the web root."
+          exit 0
